---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-admin
  namespace: argocd
  labels:
    team: platform
    managed-by: gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-admin-role
  labels:
    team: platform
    managed-by: gitops
rules:
  # Full access to all resources
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  # Access to non-resource URLs
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-admin-binding
  labels:
    team: platform
    managed-by: gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-admin-role
subjects:
  - kind: ServiceAccount
    name: platform-admin
    namespace: argocd
  # Add your actual users here later
  # - kind: User
  #   name: salwan@company.com
  #   apiGroup: rbac.authorization.k8s.io
