apiVersion: v1
kind: ResourceQuota
metadata:
  name: stage-quota
  namespace: is-team-stage
spec:
  hard:
    requests.cpu: "15"
    requests.memory: 30Gi
    limits.cpu: "30"
    limits.memory: 60Gi
    persistentvolumeclaims: "8"
    services.loadbalancers: "2"
