apiVersion: v1
kind: Namespace
metadata:
  name: app-dev
  labels:
    environment: dev
    managed-by: gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-staging
  labels:
    environment: staging
    managed-by: gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-production
  labels:
    environment: production
    managed-by: gitops
